name: slc_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.10.0
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.1+2
  jiffy: ^3.0.1
  package_info: ^0.4.3+2
  version: ^1.2.0
  flutter_staggered_animations: ^0.1.2
  modal_bottom_sheet: ^1.0.0+1
  flutter_vector_icons: ^0.2.1
  http: ^0.12.2
  rxdart: ^0.25.0
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  flutter_native_splash: ^0.1.8

flutter_native_splash:
  image: assets/img/logo.png
  color: "#006940"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/botao.png"


flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/img/
  - assets/img/ilustracoes/
  - assets/fonts/
  - assets/fonts/glacialindifference/

fonts:
  - family: glacial
    fonts:
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Regular.otf
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Italic.otf
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Bold.otf