name: slc_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.10.0
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.1+2
  jiffy: ^3.0.1
  package_info: ^0.4.3+2
  version: ^1.2.0
  flutter_staggered_animations: ^0.1.2
  modal_bottom_sheet: ^1.0.0+1
  flutter_vector_icons: ^0.2.1
  http: ^0.12.2
  rxdart: ^0.25.0
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  flutter_native_splash: ^0.1.8

flutter_native_splash:
  image: assets/img/logo.png
  color: "#006940"
  android_disable_fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/botao.png"


flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/img/
  - assets/img/ilustracoes/
  - assets/fonts/
  - assets/fonts/glacialindifference/

fonts:
  - family: glacial
    fonts:
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Regular.otf
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Italic.otf
      - asset: assets/fonts/GlacialIndifference/GlacialIndifference-Bold.otf